// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbkddgxvlqygygpfihie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impia2RkZ3h2bHF5Z3lncGZpaGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDc3MTIsImV4cCI6MjA2MDEyMzcxMn0.tCHw2s9j9RGskwfy0hPPb-9baYdCE2ue75KdidsbV4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);